library(tidyverse)
library(lubridate)
cases_county <- read_csv('./covid_cases_usa_facts.csv')
cases_county <- cases_county %>% select(-X69)
cases_county <- cases_county %>% gather(date, case,5:68)
cases_county <- cases_county %>% mutate(date=mdy(date))
cases_county <- cases_county %>% rename(county = `County Name`)
current_cases_county <- cases_county %>% filter(date=='2020-03-25')
write_csv(current_cases_county[1:1000, ], path='current_cases_county_032620_1.csv')
write_csv(current_cases_county[1001:1554, ], path='current_cases_county_032620_2.csv')